# This is a boilerplate parameters config generated for pipeline 'split_dataset'
# using Kedro 0.19.9.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.9/configuration/parameters.html

test_size: 0.2
random_state: 42
model_options:
  name: catboost
  regressor_options:
    iterations: 500               # Maximum number of boosting iterations
    learning_rate: 0.05           # Learning rate
    eval_metric: Precision        # Metric to monitor
    custom_loss :                 # Additional metrics to plot
      - AUC
      - Accuracy
      - Recall
    early_stopping_rounds: 20     # Stop if no improvement after X iterations
    od_type: Iter                 # Overfitting detection type (detect after fixed number of non-improving iterations)
    random_seed: 42
    verbose: 100                  # Print log every X iterations
    eval_fraction: 0.2
  fit_options:
    catboostclassifier__use_best_model: True
    catboostclassifier__plot: False