# This is a boilerplate parameters config generated for pipeline 'split_dataset'
# using Kedro 0.19.9.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.9/configuration/parameters.html

test_size: 0.2
random_state: 42

# Profit/lost rates based on actual defaults/non-defaults
FP_cost: 0.228696
FN_cost: 0.460871

baseline_model:
  model_options:
    name: rfc                        # randomforestclassifier
    regressor_options:
      n_estimators: 100
      random_state: 42
      criterion: log_loss
      class_weight: balanced
    # probability thresholds for model evaluation in  %
    prob_threshold:
      start: 30
      stop: 70
      step: 1

candidate_model:
  model_options:
    name: catboost                  # catboostclassifier
    regressor_options:
      iterations: 1000               # Maximum number of boosting iterations
      learning_rate: 0.05           # Learning rate
      eval_metric: PRAUC        # Metric to monitor
      custom_loss :                 # Additional metrics to plot
        - AUC
        - Accuracy
        - Recall
      early_stopping_rounds: 20     # Stop if no improvement after X iterations
      od_type: Iter                 # Overfitting detection type (detect after fixed number of non-improving iterations)
      random_seed: 42
      verbose: 100                  # Print log every X iterations
      eval_fraction: 0.2
      use_best_model: True
      loss_function: Logloss
    fit_options:
      plot: True
    prob_threshold:
      start: 30
      stop: 70
      step: 1
